version: '3.4'
services:
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_USER
      POSTGRES_USER: $POSTGRES_PASSWORD
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - backend_network
    volumes:
      - pgdata:/var/lib/postgresql/data
  paper_trail:
    image: inakri/$DOCKER_TAG
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - inakri/$DOCKER_TAG
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGPORT: 5432
      PG_HOST: db
      MIX_ENV: $MIX_ENV
    tty: true
    depends_on:
      - db
    networks:
      - backend_network
    command: ["./setup-database.sh"]

volumes:
  pgdata:
networks:
  backend_network:
    driver: bridge

